Add Github Action for Staging Deployment
smd-ka/smd-ka pull request #30
Opened 2024-07-29 19:26 UTC by Techthy

2024-08-01 11:38 UTC, Zocker1999NET requested changes

2024-08-01 11:38 UTC, Zocker1999NET commented on .github/workflows/build-push--staging.yml
> +        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git pull && docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} &&  docker compo
> `docker compose -f docker-compose.yml -f docker-compose.staging.yml up -d`

Importing a second file to overwrite some values of the first one is typically a good approach. But I’m not sure if you are aware of some potential issues with this PR so far, so I write them just in case:

The command as I have quoted will lead to Compose merging both files and then deploying it as such. The resulting configuration can be viewed by calling `docker compose -f docker-compose.yml -f docker-compose.staging.yml config`. 
So assuming we want to deploy production & staging to the same Docker host, this will break in our case because of multiple reasons:

1. Compose differentiates multiple deployments by a project-name, which defaults to the name of the directory where the first compose file is stored. Because of this, this command will then bring down the production deployment and replace it with staging. This can be fixed by setting the `--project-name` parameter for the staging environment.

2. Our containers have [fixed container_names](https://github.com/smd-ka/smd-ka/blob/eb2602b85ac2731df96c43309d6a2eee9023d0af/docker-compose.yml#L7), Because of that, Compose does not use the project name as a prefix for the container names, and because the current staging file does not change the container names, the production & the staging deployment would try to use the same container names in the global Docker container namespace, which will cause issues. This may be fixed by either overwriting the container names of *all* containers of the deployment, or by removing the fixed container names (which I think is better overall).

3. As of now, Caddy would be deployed additionally for the staging environment. This will lead to both Caddy containers trying to occupy the same public ports, which will also fail. This might be fixed by overwriting the ports argument. But then the second cannot gain any certificates from Let’s Encrypt. So, I would propose splitting up the Caddy container into its own compose file & then to deploy it only with one of both environments and letting that reverse proxy the second environment as well. However, that is not so trivial to implement.

4. The backend containers of both setups will share their data directories, which might lead to issues because the backend is probably not aware of that. I assume they need write access to these directories, then it would be helpful to use different ones for production & staging or to move that data into volumes. (Volume names are also prefixed with the project name, which is why that’s not a problem for the caddy container. In case of read-only directories, this should not be an issue as both containers cannot interfere with each other.)

2024-08-01 11:45 UTC, Techthy commented on .github/workflows/build-push--staging.yml
> +        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git pull && docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} &&  docker compo
upsi yeah I was aware that this is not working (yet) and also of most of the issues you pointed out. I should have maked this as a draft I guess. (Just created this PR to test but then didn't finish it)

2024-09-24 15:39 UTC, Techthy commented
This approach has been abandoned by me. Thanks for all the advice @Zocker1999NET . Absolted by #47

2024-09-24 15:39 UTC, closed without merging

2024-09-24 15:39 UTC, Techthy commented
This approach has been abandoned by me. Thanks for all the advice @Zocker1999NET . Absolted by #47

2024-09-24 15:39 UTC, Techthy commented
This approach has been abandoned by me. Thanks for all the advice @Zocker1999NET