Update About Us Page and exchange header image
smd-ka/smd-ka pull request #34
Opened 2024-08-05 19:54 UTC by Techthy

2024-08-06 10:50 UTC, Zocker1999NET requested changes
thanks for your work on redoing the about us page ❤️

* most crucial thing first: some of the pictures (all marked) you deleted are still referenced in about/mitarbeiten. I'm not sure about the susposed state of that page, but it seems that this page is still linked to: https://github.com/smd-ka/smd-ka/blob/c7aee003464e860dc2e2fedbcfcf80b4a429ca9a/frontend/src/routes/%2Blayout.svelte#L53-L56
* text seems mostly fine, I marked some small mistakes
* I found one new todo, also marked

2024-08-06 10:50 UTC, Zocker1999NET commented on frontend/src/routes/about/us/+page.svelte
> +	<!-- TODO add Leiter Block -->
I'm not sure if that todo was just glanced over or if you want to replace it at a later time. If this is for a later time, it should be fine.

2024-08-06 10:50 UTC, Zocker1999NET commented on frontend/src/routes/about/us/+page.svelte
> +					Liste Aller Hochschul-SMD Gruppen
```suggestion
					Liste aller Hochschul-SMD Gruppen
```
not required, but seems more correct to me

2024-08-06 10:50 UTC, Zocker1999NET commented on frontend/src/routes/about/us/+page.svelte
> +				Neben der Hochschul-SMD gibt es auch noch die Schüler-SMD und Akademiker SMD. Falls dich die
```suggestion
				Neben der Hochschul-SMD gibt es auch noch die Schüler-SMD und Akademiker-SMD. Falls dich die
```

2024-08-06 10:50 UTC, Zocker1999NET commented on frontend/src/routes/about/us/+page.svelte
> +				Wir lieben es auch uns überregional zu vernetzen und uns auszutauschen. Dafür gibt es zwei
```suggestion
				Wir lieben es auch, uns überregional zu vernetzen und auszutauschen. Dafür gibt es zwei
```
* comma because of [D125, point 3](https://www.duden.de/sprachwissen/rechtschreibregeln/komma#D125) (I only added this link because I needed to look it up myself to be sure that this is non-optional.)
* leaving `uns` out sounds more fluent to me, but your version should be correct as well

2024-08-06 10:50 UTC, Zocker1999NET commented on frontend/src/lib/assets/pages/home/schloss.jpg
good improvement 👍

2024-08-06 10:50 UTC, Zocker1999NET commented on frontend/src/lib/assets/about/denken.png
this file is still referenced by https://github.com/smd-ka/smd-ka/blob/c7aee003464e860dc2e2fedbcfcf80b4a429ca9a/frontend/src/routes/about/mitarbeiten/%2Bpage.svelte#L7 (but I do not know if this page is still publicly available)

2024-08-06 10:50 UTC, Zocker1999NET commented on frontend/src/lib/assets/about/erleben.png
this file is still referenced by https://github.com/smd-ka/smd-ka/blob/c7aee003464e860dc2e2fedbcfcf80b4a429ca9a/frontend/src/routes/about/mitarbeiten/%2Bpage.svelte#L9 (but I do not know if this page is still publicly available)

2024-08-06 10:50 UTC, Zocker1999NET commented on frontend/src/lib/assets/about/glauben.png
this file is still referenced by https://github.com/smd-ka/smd-ka/blob/c7aee003464e860dc2e2fedbcfcf80b4a429ca9a/frontend/src/routes/about/mitarbeiten/%2Bpage.svelte#L8 (but I do not know if this page is still publicly available)

2024-08-06 10:50 UTC, Zocker1999NET commented on frontend/src/lib/assets/about/leitungsteam.png
this file is still referenced by https://github.com/smd-ka/smd-ka/blob/c7aee003464e860dc2e2fedbcfcf80b4a429ca9a/frontend/src/routes/about/mitarbeiten/%2Bpage.svelte#L10 (but I do not know if this page is still publicly available)

2024-08-06 11:07 UTC, Techthy commented on frontend/src/routes/about/us/+page.svelte
> +	<!-- TODO add Leiter Block -->
It for later as I do not have an image and text yet from the new team

2024-08-06 12:10 UTC, Techthy commented
I updated the tailwind version. Unfortunately I noticed a spacing but but was so far unable to fix it. Will try again in the future

2024-08-07 10:41 UTC, Zocker1999NET approved these changes
In my opinion, you can push that now. But, just as a heads up, while testing the page locally, I found two issues which can be seen in following screenshot (left: this branch, right: main on production):

![image](https://github.com/user-attachments/assets/8a26b6df-9823-42f1-8833-9cd25a9fcab7)

1. on the `about/mitarbeiten` page, the teams do not load/show
2. (happens on any page without head banner) when navigating from a page with a head banner (like the homepage) to one without (like `about/mitarbeiten`, the navbar on the top stays transparent. I see this in both Firefox & Chrome. It is non-transparent when pressing F5 & when navigating only pages without, but once it becomes transparent, it stays that way.

both issues do not happen for me on the production server & when deploying main locally as well, so it seems these issues are triggered by changes here.

2024-08-07 12:00 UTC, merged